# Numpy

NumPy es una biblioteca para el lenguaje de programación Python que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas.

In [1]:
import numpy as np

## Fundamentos

Un **array** es una estructura de datos que almacena datos del mismo tipo. 

In [3]:
my_arr = np.array([1,2,3,4])
my_arr

array([1, 2, 3, 4])

#### Podemos crear arrays de varias dimensiones

In [13]:
my_arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
my_arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Podemos crear arrays lleno de ceros

In [18]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### Podemos crear arrays lleno de unos

In [25]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### Podemos utilizar tuplas para definir las dimensiones de nuestros arrays

In [64]:
multidimensional = np.ones((2,2,2,3))
multidimensional

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

In [43]:
type(multidimensional)

numpy.ndarray

#### Existen alternativas para **np.zeros**

In [57]:
np.empty([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

#### Podemos crear arrays llenos de un valor particular

In [66]:
np.full((3,2), 10)

array([[10, 10],
       [10, 10],
       [10, 10]])

In [70]:
np.full((2,3), ['s', '1', '3'])

array([['s', '1', '3'],
       ['s', '1', '3']], dtype='<U1')