## **Librerias**

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.options.display.max_columns = False

## **Introducción a Numpy**

### **Arrays**

<ul>
    <li>Son la estructura central de <strong>Numpy.</strong></li>
    <li>Representan datos de una manera estructurada.</li>
    <li>Indexado.</li>
    <li>Permite acceder a uno o varios elementos.</li>
</ul>

**Creación de arrays**

In [31]:
# Creamos un array unidimensional
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# Creamos un array bidimensional
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
# Vemos que efectivamente es un array
type(a)

numpy.ndarray

In [34]:
# Vemos las dimensiones del array
b.shape

(2, 3)

**Llamando a los elementos**

In [35]:
# Seleccionamos un elemento por el indice del array
a[0]

1

In [36]:
# Tambien funciona con arrays bidimensionales
b[0]

array([1, 2, 3])

In [37]:
# Y tambien podemos traer un elemento en especifico
b[0][1]

2

In [19]:
b[0, 1]

2

In [38]:
# Podemos usar slicing para llamar varios elementos a la vez
a[:4]

array([1, 2, 3, 4])

In [39]:
# Traer varios elementos con algunas reglas (En este caso de dos en dos)
a[::2]

array([1, 3, 5, 7, 9])

In [ ]:

# Aplicamos slicin