## **Librerias**

In [4]:
import pandas as pd
import numpy as np

In [5]:
pd.options.display.max_columns = False

## **1. Introducción a Numpy**

### **1.1 Arrays**

<ul>
    <li>Son la estructura central de <strong>Numpy.</strong></li>
    <li>Representan datos de una manera estructurada.</li>
    <li>Indexado.</li>
    <li>Permite acceder a uno o varios elementos.</li>
</ul>

#### **Creación de arrays**

In [4]:
# Creamos un array unidimensional
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Creamos un array bidimensional
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# Vemos que efectivamente es un array
type(a)

numpy.ndarray

In [7]:
# Vemos las dimensiones del array
b.shape

(3, 3)

#### **Llamando a los elementos**

In [8]:
# Seleccionamos un elemento por el indice del array
a[0]

1

In [9]:
# Tambien funciona con arrays bidimensionales
b[0]

array([1, 2, 3])

In [10]:
# Y tambien podemos traer un elemento en especifico
b[0][1]

2

In [11]:
b[0, 1]

2

In [12]:
# Podemos usar slicing para llamar varios elementos a la vez
a[:4]

array([1, 2, 3, 4])

In [13]:
# Traer varios elementos con algunas reglas (En este caso de dos en dos)
a[::2]

array([1, 3, 5, 7, 9])

In [14]:
# Aplicamos slicing en una matriz, en este caso primero indicamos las filas y luego las columnas
b[1:, :2]

array([[4, 5],
       [7, 8]])

#### **Tipo de datos**

In [26]:
# Determinar el tipo de datos del array
a = np.array([1, 2, 3, 4], dtype='float64')
a.dtype

dtype('float64')

In [28]:
# Cambiar el tipo de datos
a.astype(np.int64)

array([1, 2, 3, 4], dtype=int64)

#### **Crear arrays con numpy**

In [30]:
# Crear un array de una secuencia
a = np.arange(1, 11, 2)
a

array([1, 3, 5, 7, 9])

In [29]:
# Crear un array de ceros
b = np.zeros((10,2))
b

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
# Crear un array de unos
c = np.ones(10)
c

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
# Crear un array de una secuencia distribuida
d = np.linspace(0, 10, 10)
d

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [37]:
# Crear una matriz identidad
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
# Crear un array con números aleatorios entre 0 y 1
f = np.random.rand(2, 2)
f

array([[0.88114882, 0.0749444 ],
       [0.11253897, 0.10903496]])

In [50]:
# Crear un array con números aleatorios entre un rango
g = np.random.randint(1, 10, (3, 3))
g

array([[1, 6, 6],
       [3, 4, 2],
       [1, 5, 2]])