## **Librerias**

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.options.display.max_columns = False

## **1. Introducción a Numpy**

### **1.1 Arrays**

<ul>
    <li>Son la estructura central de <strong>Numpy.</strong></li>
    <li>Representan datos de una manera estructurada.</li>
    <li>Indexado.</li>
    <li>Permite acceder a uno o varios elementos.</li>
</ul>

#### **Creación de arrays**

In [3]:
# Creamos un array unidimensional
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Creamos un array bidimensional
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Vemos que efectivamente es un array
type(a)

numpy.ndarray

In [6]:
# Vemos las dimensiones del array
b.shape

(3, 3)

#### **Llamando a los elementos**

In [7]:
# Seleccionamos un elemento por el indice del array
a[0]

1

In [8]:
# Tambien funciona con arrays bidimensionales
b[0]

array([1, 2, 3])

In [9]:
# Y tambien podemos traer un elemento en especifico
b[0][1]

2

In [10]:
b[0, 1]

2

In [11]:
# Podemos usar slicing para llamar varios elementos a la vez
a[:4]

array([1, 2, 3, 4])

In [12]:
# Traer varios elementos con algunas reglas (En este caso de dos en dos)
a[::2]

array([1, 3, 5, 7, 9])

In [13]:
# Aplicamos slicing en una matriz, en este caso primero indicamos las filas y luego las columnas
b[1:, :2]

array([[4, 5],
       [7, 8]])

#### **Tipo de datos**

In [14]:
# Determinar el tipo de datos del array
a = np.array([1, 2, 3, 4], dtype='float64')
a.dtype

dtype('float64')

In [15]:
# Cambiar el tipo de datos
a.astype(np.int64)

array([1, 2, 3, 4], dtype=int64)

#### **Crear arrays con numpy**

In [16]:
# Crear un array de una secuencia
a = np.arange(1, 11, 2)
a

array([1, 3, 5, 7, 9])

In [17]:
# Crear un array de ceros
b = np.zeros((10,2))
b

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
# Crear un array de unos
c = np.ones(10)
c

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
# Crear un array de una secuencia distribuida
d = np.linspace(0, 10, 10)
d

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [20]:
# Crear una matriz identidad
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# Crear un array con números aleatorios entre 0 y 1
f = np.random.rand(2, 2)
f

array([[0.25408841, 0.11227761],
       [0.82544854, 0.29678811]])

In [22]:
# Crear un array con números aleatorios entre un rango
g = np.random.randint(1, 10, (3, 3))
g

array([[9, 1, 8],
       [9, 8, 5],
       [4, 5, 1]])

In [23]:
g

array([[9, 1, 8],
       [9, 8, 5],
       [4, 5, 1]])

#### **Funciones principales**

##### **Elemento mayor**

In [24]:
# Traer el elemento mayor
g.max()

9

In [25]:
# Traer el elemento mayor por columnas
g.max(0)

array([9, 8, 8])

In [26]:
# Traer el elemento mayor por filas
g.max(1)

array([9, 9, 5])

In [27]:
# Indica el indice en el que esta el elemento mayor
g.argmax()

0

##### **Elemento menor**

In [28]:
# Traer el elemento menor
g.min()

1

In [29]:
# Traer el elemento menor por columnas
g.min(0)

array([4, 1, 1])

In [30]:
# Traer el elemento menor por filas
g.min(1)

array([1, 5, 1])

In [31]:
# Indica el indice en el que esta el elemento menor
g.argmin()

1

##### **Rangos**

In [32]:
# Diferencia entre el elemento menor y el elemento mayor
g.ptp()

8

In [33]:
# Trae el valor del percentil que especifiquemos
np.percentile(g, 50)

5.0

##### **Funciones estadisticas**

In [34]:
# Ordenear los valores de menor a mayor
g.sort()
g

array([[1, 8, 9],
       [5, 8, 9],
       [1, 4, 5]])

In [35]:
# Calcular la media de un array
np.mean(g)

5.555555555555555

In [36]:
# Calcular la mediana de un array
round(np.median(g),2)

5.0

In [37]:
# Calcular la desviación estándar de un array
round(np.std(g),2)

2.99

In [38]:
# Calcular la varianza de un array
round(np.var(g),2)

8.91

##### **Combinar arrays**

In [39]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
b = np.array([7,8,9])
b

array([7, 8, 9])

In [41]:
# Ajustamos las dimensiones de nuestros array
b = np.expand_dims(b, axis=0)

In [42]:
# Combinamos los arrays
c = np.concatenate((a,b), axis=0)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
c.copy()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### **Condiciones**

In [44]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
# Filtrar los elementos de un array con una condición
a[a>5]

array([6, 7, 8, 9])

In [46]:
# Cambiar el valor de los elementos de un array con una condicion
a[a>5]=10
a

array([ 1,  2,  3,  4,  5, 10, 10, 10, 10])

#### **Operaciones**

In [48]:
a = np.array([10, 20, 30])
a

array([10, 20, 30])

##### **Operaciones entre arrays y escalares**

In [53]:
# Suma
a + 2

array([12, 22, 32])

In [54]:
# Resta
a - 2

array([ 8, 18, 28])

In [55]:
# Multiplicación
a * 2

array([20, 40, 60])

In [56]:
# División
a / 2

array([ 5., 10., 15.])

##### **Operaciones entre arrays**

In [58]:
# Suma de arrays
a + a

array([20, 40, 60])

In [61]:
# Resta de arrays
a - a

array([0, 0, 0])

##### **Operaciones entre matrices**

In [63]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
# Produco punto
np.matmul(b, b.T)

array([[14, 32],
       [32, 77]])

In [69]:
b@b.T

array([[14, 32],
       [32, 77]])

In [72]:
np.dot(b, b.T)

array([[14, 32],
       [32, 77]])